---
title: "Assignment 1: Introduction"
author: "Samantha Burch"
output: pdf_document
geometry: margin=2.54cm
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1. Change "Student Name" on line 3 (above) with your name.
3. Work through the steps, **creating code and output** that fulfill each instruction.
4. Be sure to **answer the questions** in this assignment document.
6. When you have completed the assignment, **Knit** the text and code into a single PDF file.
8. After Knitting, submit the completed exercise (PDF file) to the dropbox in Sakai. Add your last name into the file name (e.g., "Salk_A03_Introduction.Rmd") prior to submission.

The completed exercise is due on Tuesday, January 14th at 1:00 pm.

## 1) Discussion Questions

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: I have not had any previous experience with R nor Git. During undergrad, I took both Intro to Statistics and Strategies for Environmental Inquiry. In the latter, we covered the following: •	Understand how and when to use fundamental quantitative and qualitative research methods, as well as recognize their limitations.
•	Use and interpret empirical design and fundamental statistical concepts in ecology and environmental studies, as well as recognize their limitations. 
•	Understand a breadth of terminology on the scientific process, value systems, policy analysis, stakeholder analysis, and critical inquiry.
Currently, I am working in NVivo, conducting qualitative analysis. 

2. Are there any components of the course about which you feel confident?

> Answer: I feel confident in my ability to ask questions and put in extra work whenever/wherever needed, as working with quantitative data is relatively new to me. As a visual learner, I also feel fairly confident in my ability to visualize and communicate my findings from the data sets.

3. Are there any components of the course about which you feel apprehensive?

> Answer: Given I have not had a stats course in quite some time nor experience with R, I look forward to the laid out format of this class. I am looking forward to gaining proficiency in the language and application of R software, as it is an incresingly desired skillset within the private sector. Companies are working to further link sustainability and data science.  


## 2) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository  and that you have updated your course README file. 

> Answer: https://github.com/sfburch/Environmental_Data_Analytics_2020.git


